chat_login/urls.py
from django.urls import path
from django.conf import  settings
from django.conf.urls.static import static

from . import views

app_name='chat_login'

urlpatterns = [
    path('', views.log_in, name='log_in'),
    path('registration/', views.sign_up, name='sign_up'),
    path('logout/', views.log_out, name='log_out'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat_main/urls.py
from django.urls import path
from . import views

app_name='chat_main'

urlpatterns = [
    path('', views.index, name='index'),
    path('newgroup/<str:room_name>/', views.room, name='room'),
    path('<str:name>/', views.user_message, name='user_message'),
    path('newgroup/', views.new_group, name='new_group'),
    path('deletegroup/', views.delete_group, name='delete_group'),
    path('deletegroup/<str:group>/', views.confirm, name='confirm'),
    path('editgroup/<str:room_name>/', views.edit_group, name='edit_group'),
    path('leave_group/<str:group>/', views.leave_group, name='leave_group'),
    path('find_group/', views.find_group, name='find_group'),
]

chat_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat_login.urls', namespace='chat_login')),
    path('chat/', include('chat_main.urls', namespace='chat_main')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat_login/models.py
from django.db import models

# Create your models here.

chat_main/models.py
from django.db import models
from django.contrib.auth.models import User


class Groups(models.Model):
    name_of_group = models.CharField(max_length=50, blank=False)
    members = models.ManyToManyField(User, blank=True, related_name='access')

    def __str__(self):
        return self.name_of_group

chat_login/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.Form):
    username = forms.CharField(max_length = 100)
    password = forms.CharField(widget=forms.PasswordInput())

chat_main/forms.py
from django import forms

from .models import Groups


class NewGroupForm(forms.ModelForm):
    class Meta:
        model = Groups
        fields = ['name_of_group', 'members']

class FindGroupform(forms.ModelForm):
    class Meta:
        model = Groups
        fields = ['name_of_group']

chat_login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .forms import UserForm


def sign_up(request):
    if request.user.is_authenticated:
        return redirect('chat_main:index')

    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = User.objects.create_user(username=form.cleaned_data['username'], 
                                            password=form.cleaned_data['password1'],
                                            )           
            user.save()
            return redirect('chat_login:log_in')

        else:
            return redirect('chat_login:sign_up')

    else:
        form = UserCreationForm()

    return render(request, 'chat_login/sign_up.html', {
                'form':form,
                })


def log_in(request):
    if request.user.is_authenticated:
        return redirect('chat_main:index')

    if request.method == 'POST':
        form = UserForm(request.POST)
        
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], 
                                password=form.cleaned_data['password'],
                                )

            if user:
                login(request, user)
                return redirect('chat_main:index')

    form = UserForm()
    return render(request, 'chat_login/log_in.html', {
                'form': form,
                })


@login_required
def log_out(request):
    logout(request)
    return redirect('chat_login:log_in')

chat_main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse

from .forms import NewGroupForm, FindGroupform
from .models import Groups, User


def index(request):
    group_names = Groups.objects.all()
    who_ask = request.user
    form = FindGroupform()

    return  render(request, 'chat_main/index.html', {
                'group_names': group_names,
                'who_ask': who_ask,
                'form': form,
                })


def room(request, room_name):
    group_names = Groups.objects.all()
    users = Groups.objects.get(name_of_group=room_name)
    who_ask = request.user

    return render(request, 'chat_main/room.html', {
                'room_name': room_name,
                'group_names': group_names,
                'users': users,
                'who_ask': who_ask,
                })


def new_group(request):
    form_group = NewGroupForm(request.POST or None)

    if request.method == 'POST':
        form_group.save()

    if form_group.is_valid():   
        form_group.save()
        return(redirect('chat_main:index'))

    else:
        form_group = NewGroupForm()

    return render(request, 'chat_main/new_group.html', {
                'form_group': form_group, 
                'new': True,
                })


def user_message(request, name):
    group_names = Groups.objects.all()
    user1 = User.objects.get(username=name)
    user2 = User.objects.get(username=request.user)
    print(user1, user2)
    group = Groups.objects.create(name_of_group='{}_chat'.format(user1.username))
    group.members.set([user1, user2])
    return render(request, 'chat_main/room.html', {
                'room_name': group.name_of_group,
                'group_names': group_names,
                'users': group,
                'who_ask': user2,
                })

def find_group(request):
    if request.method == 'GET':
        try:
            group = Groups.objects.get(name_of_group=request.GET['name_of_group'])

            return redirect('chat_main:room', group)

        except Groups.DoesNotExist:
            
            return HttpResponse('Group does not exist')

        else:

            return HttpResponse('Something went wrong')


def edit_group(request, room_name):
    group = Groups.objects.get(name_of_group=room_name)
    form_group = NewGroupForm(request.POST or None, instance=group)

    if request.method == 'POST':
        form_group.save()

    if form_group.is_valid():   
        form_group.save()
        return(redirect('chat_main:index'))
    
    return render(request, 'chat_main/new_group.html', {
                'form_group': form_group, 
                'new': False,
                })


def delete_group(request):
    groups = Groups.objects.filter(members=request.user)
    return render(request, 'chat_main/delete_group.html', {
                'groups': groups,
                })


def confirm(request, group):
    to_delete = Groups.objects.get(name_of_group=group)
    
    if request.method == 'POST':
        to_delete.delete()
        return redirect('chat_main:index')

    return render(request, 'chat_main/confirm.html', {
                'to_delete': to_delete,
                'leave': False,
                })


def leave_group(request, group):
    to_delete = Groups.objects.get(name_of_group=group)
    user = request.user

    if request.method == 'POST':
        to_delete.members.remove(user)
        return redirect('chat_main:index')

    return render(request, 'chat_main/confirm.html', {
                'to_delete': to_delete,
                'leave': True,
                'user': user,
                })

chat_login/templates/chat_login/log_in.html
{% extends 'chat_main/base.html' %}
{% block title %} Log in {% endblock %}

{% load bootstrap4 %}

{% block content_unlogged %} 
    <div class="card col-md-5">
        <div class="card-body">
            <h5 class="card-title"> Log in </h5>
                <form action="{% url 'chat_login:log_in' %}" method='POST'>
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-secondary"> Log in </button> 
                </form>
                <a href="{% url 'chat_login:sign_up' %}">
                    <button type='submit' class="btn btn-secondary"> Go to registration </button>
                </a>
        </div>
    </div>
{% endblock %}

chat_login/templates/chat_login/sign_up.html
{% extends 'chat_main/base.html' %}
{% block title %} Sign up {% endblock %}

{% load bootstrap4 %}

{% block content_unlogged %} 
    <div class="card col-md-5">
        <div class="card-body">
            <h5 class="card-title">Sign up</h5>
                <form action="{% url 'chat_login:sign_up' %}" method='POST'>
                
                    {% csrf_token %}
                    {% bootstrap_form form %}

                    <a href="{% url 'chat_login:log_in' %}"><button type='submit' class="btn btn-secondary"> Sign up </button></a>
                    
                </form>
                <a href="{% url 'chat_login:log_in' %}">
                    <button type='submit' class="btn btn-secondary"> Go to login </button>
                </a>
        </div>
    </div>
{% endblock %}

chat_main/templates/chat_main/base.html
{% load static %}
{% load bootstrap4 %}

<html>
    <head>
        <title>
            {% block title %} {% endblock %}
        </title>

        <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                    {% if user.is_authenticated %}
                        <a class="navbar-brand" href="{% url 'chat_main:index' %}"> Home </a> 
                        <a class="nav-link active" href="{% url 'chat_login:log_out' %}"> Log out </a> 
                        
                    {% else %}
                        <a class="navbar-brand" href="{% url 'chat_main:index' %}"> Home </a> 
                        <a class="nav-link active" href="{% url 'chat_login:log_in' %}"> Log in </a> 
                        <a class="nav-link active" href="{% url 'chat_login:sign_up' %}"> Sign up </a>
                    {% endif %}
            </div>
        </nav>
        
        {% if user.is_authenticated %}
            <div class="row">
                <div class="left-nav col-md-2">
                        <li class="nav-item">
                            <a href="{% url 'chat_main:new_group' %}" style="text-decoration: None; color: black; text-shadow:None; font:bold; font-size: 14px;">
                                <i class="fas fa-plus-circle"></i> Create new group 
                            </a>
                        </li>

                        {% if room_name %}
                            <li class="nav-item">
                                <a href="{% url 'chat_main:edit_group' room_name %}" style="text-decoration: None; color: black; text-shadow:None; font:bold; font-size: 14px;">
                                    <i class="fas fa-edit"></i> Edit group 
                                </a>
                            </li>
                        {% endif %}

                        <li class="nav-item">
                            <a href="{% url 'chat_main:delete_group' %}" style="text-decoration: None; color: black; text-shadow:None; font:bold; font-size: 14px;">
                                <i class="fas fa-minus-circle"></i> Delete group
                            </a>
                        </li>
                        <br>
                        {% if group_names %}
                            <li class="nav-item">
                                <a style="text-decoration: None; color: black; text-shadow:None; font:bold; font-size: 18px; text-decoration: underline;">
                                    <i class="fas fa-users"></i> Groups: 
                                </a>
                            </li>               
                            {% for group in group_names %} 
                                {% if who_ask in group.members.all %}
                                    <li class="nav-item">
                                        <a style='nav_a' href="{% url 'chat_main:room' group %}"> {{ group }} </a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                </div>
            <div class='col-md-10 justify-content-center'>   

            {% block content %} 

            {% endblock %}
            </div>
        </div>

        {% else %}
            <div class="row">
                <div class="col-md-12 justify-content-center">

                    {% block content_unlogged %} 

                    {% endblock %}
                </div>
            </div>
        {% endif %}

        {% block scripts %}
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
            <script src="https://kit.fontawesome.com/087106493e.js" crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>

chat_main/templates/chat_main/confirm.html
{% extends 'chat_main/base.html' %}
{% block title %} Confirm {% endblock %}

{% block content %}
        <div class="card col-md-9">
            <div class="card-body">
                {% if leave == False %}
                    <h5 class="card-title"> Are you sure you want to delete {{to_delete}}? </h5>
                {% else %}
                    <h5 class="card-title"> Are you sure you want to leave {{to_delete}}? </h5>
                {% endif %}
                <form method='POST'>
                    {% csrf_token %}
                    {% if leave == False %}
                        <button class="btn btn-danger" type="submit">
                            <i class="fas fa-minus-circle"></i> Delete 
                        </button>
                    {% else %}
                        <button class="btn btn-danger" type="submit">
                            <i class="fas fa-minus-circle"></i> Leave 
                        </button>
                    {% endif %}
                </form>
                <a href="{% url 'chat_main:index' %}">
                    <button class="btn btn-secondary">
                        <i class="fas fa-undo"></i> Back 
                    </button>
                </a>
            </div>
        </div>
{% endblock %}

{% block content_unlogged %}
    <div class="card col-md-9">
        <div class="card-body">
            <p><strong> You have no access to this site... </strong></p>
            <p> Please, log in or register </p>
            <a href="{% url 'chat_login:log_in' %}"><button class="btn btn-secondary"> Log in </button></a>
            <a href="{% url 'chat_login:sign_up' %}"><button class="btn btn-secondary"> Sign up </button></a>
        </div>
    </div>
{% endblock %}

chat_main/templates/chat_main/delete_group.html
{% extends 'chat_main/base.html' %}
{% block title %} DeleteGroup {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="card col-9">
            <div class="card-body">
                <h5 class="card-title"> Choose group to delete: </h5>
                {% if groups %}
                    {% for group in groups %} 
                        <ul>
                            <a href="{% url 'chat_main:confirm' group %}" class="delete_a"> {{group}} </a>
                        </ul>
                    {% endfor %}
                {% endif %}
                <a href="{% url 'chat_main:index' %}">
                    <button class="btn btn-outline-secondary" style="margin-left: 80%"><i class="fas fa-undo"></i> Back </button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

{% block content_unlogged %}
    <div class="card col-md-9">
        <div class="card-body">
            <p><strong> You have no access to this site... </strong></p>
            <p> Please, log in or register </p>
            <a href="{% url 'chat_login:log_in' %}"><button class="btn btn-secondary"> Log in </button></a>
            <a href="{% url 'chat_login:sign_up' %}"><button class="btn btn-secondary"> Sign up </button></a>
        </div>
    </div>
{% endblock %}

chat_main/templates/chat_main/index.html
{% extends 'chat_main/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %} Chat Rooms {% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <div class="card col-9">
                <div class="card-body">
                    <h5 class="card-title"> Find group: </h5>
                    <form action = "{% url 'chat_main:find_group' %}" method='GET'>
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button class='btn btn-secondary' type="submit"> Search <i class="fas fa-search"></i></button>
                    </form>   
                </div>
            </div>
        </div>  

    {% else %}
        <div class="card col-9">
            <div class="card-body">
                <p><strong> You have no access to this site... </strong></p>
                <p> Please, log in or register </p>
                <a href="{% url 'chat_login:log_in' %}">
                    <button class="btn btn-secondary"> Log in </button>
                </a>
                <a href="{% url 'chat_login:sign_up' %}">
                    <button class="btn btn-secondary"> Sign up </button>
                </a>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block content_unlogged %}
    <div class="card col-md-9">
        <div class="card-body">
            <p><strong> You have no access to this site... </strong></p>
            <p> Please, log in or register </p>
            <a href="{% url 'chat_login:log_in' %}"><button class="btn btn-secondary"> Log in </button></a>
            <a href="{% url 'chat_login:sign_up' %}"><button class="btn btn-secondary"> Sign up </button></a>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $( function () {
            $("#group_search").autocomplete({
                source: '{% url 'chat_main:index' %}'
                                    
            });
        });
    </script> 
{% endblock %}

chat_main/templates/chat_main/new_group.html
{% extends 'chat_main/base.html' %}
{% load bootstrap4 %}

{% block title %} CreateGroup {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="card col-9">
            <div class="card-body">
                {% if new == True %}    
                    <h5 class="card-title"> Create new group </h5>
                {% else %}
                    <h5 class="card-title"> Edit group </h5>
                    {% endif %}
                <form method='POST'> 
                    {% csrf_token %}
                    {% bootstrap_form form_group %}
                    {% if new == True %}
                        <button type="submit" class="btn btn-secondary"> Create </button>
                    {% else %}
                        <button type="submit" class="btn btn-secondary">
                            <i class="fas fa-edit"></i> Edit 
                        </button>
                    {% endif %}
                </form>
                <a href="{% url 'chat_main:index' %}">
                    <button class="btn btn-secondary">
                        <i class="fas fa-undo"></i> Back 
                    </button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

{% block content_unlogged %}
    <div class="card col-md-9">
        <div class="card-body">
            <p><strong> You have no access to this site... </strong></p>
            <p> Please, log in or register </p>
            <a href="{% url 'chat_login:log_in' %}"><button class="btn btn-secondary"> Log in </button></a>
            <a href="{% url 'chat_login:sign_up' %}"><button class="btn btn-secondary"> Sign up </button></a>
        </div>
    </div>
{% endblock %}

chat_main/templates/chat_main/room.html
{% extends 'chat_main/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %} Chat Room {% endblock %}

{% block content %} 
    <div class='container-fluid'>
        <div class="row justify-content-end">
            <div class='col-md-10'>
                <div class='chat_box'>
                    <div class="row justify-content-center">
                        <h5> {{ room_name }} </h5>
                    </div>
                    <div class="row justify-content-center">
                        <textarea id="chat-log" class='chat_log'></textarea>
                    </div>
                    <div class="row justify-content-center">
                        <input id="chat-message-input" type="text" style='width: 31rem'>
                        <input id="chat-message-submit" type="button" value="Send" class="btn btn-secondary">
                        {{ room_name|json_script:"room-name" }}
                    </div>
                </div>
            </div>
    
            <div class='right-nav col-md-2'>
                <nav class="flex-column">
                    <div class="row justify-content-right">
                        <li class="nav-item">
                            <a class="a_members"> 
                                <i class="fas fa-users"></i> Members: 
                            </a>
                        </li>
                        {% if users %}
                            {% for name in users.members.all %}
                            <li class="nav-item">
                                <a class="a_names" href="{% url 'chat_main:user_message' name %}"> {{ name }} <i class="far fa-comments"></i></a>
                            </li>
                            {% endfor %}
                        {% endif %}
                        <li class="nav-item">
                            <a class="a_names_action" href="{% url 'chat_main:leave_group' room_name %}">
                                <i class="fas fa-arrow-circle-left"></i> Leave group 
                            </a>
                        </li>
                    </div>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}

{%block content_unlogged %}
    <div class="card col-md-9">
        <div class="card-body">
            <p><strong> You have no access to this site... </strong></p>
            <p> Please, log in or register </p>
            <a href="{% url 'chat_login:log_in' %}"><button class="btn btn-secondary"> Log in </button></a>
            <a href="{% url 'chat_login:sign_up' %}"><button class="btn btn-secondary"> Sign up </button></a>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);
        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/newgroup/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                }));
                messageInputDom.value = '';
            };
    </script>
{% endblock %}

chat_main/templates/chat_main/user_message.html
{{ group }}